image_name: 'airhorns/python-node'

python_versions:
  3.7.0:
    aliases: ['latest', '3', '3.7']
  3.6.6:
    aliases: ['3.6']
  3.5.6:
    aliases: ['3.5']
  2.7.15:
    aliases: ['2', '2.7']

node_versions:
  10.10.0:
    aliases: ['latest', '10']
  8.12.0:
    aliases: ['8']
  6.14.4:
    aliases: ['6']

top_level_aliases:
  latest: 'latest-latest-stretch'

bases:
  stretch:
    template_name: 'Dockerfile.debian'
    default: true
  slim-stretch:
    template_name: 'Dockerfile.debian'
  alpine3.8:
    template_name: 'Dockerfile.alpine'
    aliases: ['alpine']
