version: 2
jobs:
  
  "build 3.7.0-10.10.0-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.7.0-10.10.0-stretch dockerfiles/3.7.0-10.10.0-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.7.0-10.10.0-stretch python --version
            docker run airhorns/python-node:3.7.0-10.10.0-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.7.0-10.10.0-stretch
  
  "build 3.7.0-8.12.0-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.7.0-8.12.0-stretch dockerfiles/3.7.0-8.12.0-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.7.0-8.12.0-stretch python --version
            docker run airhorns/python-node:3.7.0-8.12.0-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.7.0-8.12.0-stretch
  
  "build 3.7.0-6.14.4-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.7.0-6.14.4-stretch dockerfiles/3.7.0-6.14.4-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.7.0-6.14.4-stretch python --version
            docker run airhorns/python-node:3.7.0-6.14.4-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.7.0-6.14.4-stretch
  
  "build 3.6.6-10.10.0-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.6.6-10.10.0-stretch dockerfiles/3.6.6-10.10.0-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.6.6-10.10.0-stretch python --version
            docker run airhorns/python-node:3.6.6-10.10.0-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.6.6-10.10.0-stretch
  
  "build 3.6.6-8.12.0-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.6.6-8.12.0-stretch dockerfiles/3.6.6-8.12.0-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.6.6-8.12.0-stretch python --version
            docker run airhorns/python-node:3.6.6-8.12.0-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.6.6-8.12.0-stretch
  
  "build 3.6.6-6.14.4-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.6.6-6.14.4-stretch dockerfiles/3.6.6-6.14.4-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.6.6-6.14.4-stretch python --version
            docker run airhorns/python-node:3.6.6-6.14.4-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.6.6-6.14.4-stretch
  
  "build 3.5.6-10.10.0-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.5.6-10.10.0-stretch dockerfiles/3.5.6-10.10.0-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.5.6-10.10.0-stretch python --version
            docker run airhorns/python-node:3.5.6-10.10.0-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.5.6-10.10.0-stretch
  
  "build 3.5.6-8.12.0-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.5.6-8.12.0-stretch dockerfiles/3.5.6-8.12.0-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.5.6-8.12.0-stretch python --version
            docker run airhorns/python-node:3.5.6-8.12.0-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.5.6-8.12.0-stretch
  
  "build 3.5.6-6.14.4-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.5.6-6.14.4-stretch dockerfiles/3.5.6-6.14.4-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.5.6-6.14.4-stretch python --version
            docker run airhorns/python-node:3.5.6-6.14.4-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.5.6-6.14.4-stretch
  
  "build 2.7.15-10.10.0-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:2.7.15-10.10.0-stretch dockerfiles/2.7.15-10.10.0-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:2.7.15-10.10.0-stretch python --version
            docker run airhorns/python-node:2.7.15-10.10.0-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:2.7.15-10.10.0-stretch
  
  "build 2.7.15-8.12.0-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:2.7.15-8.12.0-stretch dockerfiles/2.7.15-8.12.0-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:2.7.15-8.12.0-stretch python --version
            docker run airhorns/python-node:2.7.15-8.12.0-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:2.7.15-8.12.0-stretch
  
  "build 2.7.15-6.14.4-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:2.7.15-6.14.4-stretch dockerfiles/2.7.15-6.14.4-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:2.7.15-6.14.4-stretch python --version
            docker run airhorns/python-node:2.7.15-6.14.4-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:2.7.15-6.14.4-stretch
  
  "build 3.7.0-10.10.0-slim-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.7.0-10.10.0-slim-stretch dockerfiles/3.7.0-10.10.0-slim-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.7.0-10.10.0-slim-stretch python --version
            docker run airhorns/python-node:3.7.0-10.10.0-slim-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.7.0-10.10.0-slim-stretch
  
  "build 3.7.0-8.12.0-slim-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.7.0-8.12.0-slim-stretch dockerfiles/3.7.0-8.12.0-slim-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.7.0-8.12.0-slim-stretch python --version
            docker run airhorns/python-node:3.7.0-8.12.0-slim-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.7.0-8.12.0-slim-stretch
  
  "build 3.7.0-6.14.4-slim-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.7.0-6.14.4-slim-stretch dockerfiles/3.7.0-6.14.4-slim-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.7.0-6.14.4-slim-stretch python --version
            docker run airhorns/python-node:3.7.0-6.14.4-slim-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.7.0-6.14.4-slim-stretch
  
  "build 3.6.6-10.10.0-slim-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.6.6-10.10.0-slim-stretch dockerfiles/3.6.6-10.10.0-slim-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.6.6-10.10.0-slim-stretch python --version
            docker run airhorns/python-node:3.6.6-10.10.0-slim-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.6.6-10.10.0-slim-stretch
  
  "build 3.6.6-8.12.0-slim-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.6.6-8.12.0-slim-stretch dockerfiles/3.6.6-8.12.0-slim-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.6.6-8.12.0-slim-stretch python --version
            docker run airhorns/python-node:3.6.6-8.12.0-slim-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.6.6-8.12.0-slim-stretch
  
  "build 3.6.6-6.14.4-slim-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.6.6-6.14.4-slim-stretch dockerfiles/3.6.6-6.14.4-slim-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.6.6-6.14.4-slim-stretch python --version
            docker run airhorns/python-node:3.6.6-6.14.4-slim-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.6.6-6.14.4-slim-stretch
  
  "build 3.5.6-10.10.0-slim-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.5.6-10.10.0-slim-stretch dockerfiles/3.5.6-10.10.0-slim-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.5.6-10.10.0-slim-stretch python --version
            docker run airhorns/python-node:3.5.6-10.10.0-slim-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.5.6-10.10.0-slim-stretch
  
  "build 3.5.6-8.12.0-slim-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.5.6-8.12.0-slim-stretch dockerfiles/3.5.6-8.12.0-slim-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.5.6-8.12.0-slim-stretch python --version
            docker run airhorns/python-node:3.5.6-8.12.0-slim-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.5.6-8.12.0-slim-stretch
  
  "build 3.5.6-6.14.4-slim-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:3.5.6-6.14.4-slim-stretch dockerfiles/3.5.6-6.14.4-slim-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:3.5.6-6.14.4-slim-stretch python --version
            docker run airhorns/python-node:3.5.6-6.14.4-slim-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:3.5.6-6.14.4-slim-stretch
  
  "build 2.7.15-10.10.0-slim-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:2.7.15-10.10.0-slim-stretch dockerfiles/2.7.15-10.10.0-slim-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:2.7.15-10.10.0-slim-stretch python --version
            docker run airhorns/python-node:2.7.15-10.10.0-slim-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:2.7.15-10.10.0-slim-stretch
  
  "build 2.7.15-8.12.0-slim-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:2.7.15-8.12.0-slim-stretch dockerfiles/2.7.15-8.12.0-slim-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:2.7.15-8.12.0-slim-stretch python --version
            docker run airhorns/python-node:2.7.15-8.12.0-slim-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:2.7.15-8.12.0-slim-stretch
  
  "build 2.7.15-6.14.4-slim-stretch/Dockerfile":
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Build container
          command: docker build -t airhorns/python-node:2.7.15-6.14.4-slim-stretch dockerfiles/2.7.15-6.14.4-slim-stretch/.
      - run:
          name: Test container
          command: |
            docker run airhorns/python-node:2.7.15-6.14.4-slim-stretch python --version
            docker run airhorns/python-node:2.7.15-6.14.4-slim-stretch node --version
      - run:
          name: Push container
          command: |
            echo "$DOCKER_HUB_PASSWORD" | docker login --username airhorns --password-stdin
            docker push airhorns/python-node:2.7.15-6.14.4-slim-stretch
  

workflows:
  version: 2
  build:
    jobs:
    
      - "build 3.7.0-10.10.0-stretch/Dockerfile"
    
      - "build 3.7.0-8.12.0-stretch/Dockerfile"
    
      - "build 3.7.0-6.14.4-stretch/Dockerfile"
    
      - "build 3.6.6-10.10.0-stretch/Dockerfile"
    
      - "build 3.6.6-8.12.0-stretch/Dockerfile"
    
      - "build 3.6.6-6.14.4-stretch/Dockerfile"
    
      - "build 3.5.6-10.10.0-stretch/Dockerfile"
    
      - "build 3.5.6-8.12.0-stretch/Dockerfile"
    
      - "build 3.5.6-6.14.4-stretch/Dockerfile"
    
      - "build 2.7.15-10.10.0-stretch/Dockerfile"
    
      - "build 2.7.15-8.12.0-stretch/Dockerfile"
    
      - "build 2.7.15-6.14.4-stretch/Dockerfile"
    
      - "build 3.7.0-10.10.0-slim-stretch/Dockerfile"
    
      - "build 3.7.0-8.12.0-slim-stretch/Dockerfile"
    
      - "build 3.7.0-6.14.4-slim-stretch/Dockerfile"
    
      - "build 3.6.6-10.10.0-slim-stretch/Dockerfile"
    
      - "build 3.6.6-8.12.0-slim-stretch/Dockerfile"
    
      - "build 3.6.6-6.14.4-slim-stretch/Dockerfile"
    
      - "build 3.5.6-10.10.0-slim-stretch/Dockerfile"
    
      - "build 3.5.6-8.12.0-slim-stretch/Dockerfile"
    
      - "build 3.5.6-6.14.4-slim-stretch/Dockerfile"
    
      - "build 2.7.15-10.10.0-slim-stretch/Dockerfile"
    
      - "build 2.7.15-8.12.0-slim-stretch/Dockerfile"
    
      - "build 2.7.15-6.14.4-slim-stretch/Dockerfile"
    